language: python
python:
    - "2.7"
script:
    - cd python
    - py.test test.py
    - cd ../
    - gcc -Wall c/main.c -o brainfuck
    - gcc -Wall c/test.c -o test
    - ./test
    - cd java
    - mvn clean compile test
